package com.findwise;


import java.util.Objects;
import java.util.StringJoiner;

public class DefaultIndexEntry implements IndexEntry {
    private String Id;
    private double Score;

    // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    public DefaultIndexEntry(String Id, double Score) {
        this.Id = Objects.requireNonNull(Id);
        this.Score = Score;
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    @Override
    public String getId() {
        return Id;
    }

    @Override
    public void setId(String Id) {
        this.Id = Objects.requireNonNull(Id);
    }

    @Override
    public double getScore() {
        return Score;
    }

    @Override
    public void setScore(double Score) {
        this.Score = Score;
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        DefaultIndexEntry that = (DefaultIndexEntry) o;

        return Objects.equals(this.getId(), that.getId()) && Objects.equals(this.getScore(), that.getScore());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getScore());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("Id=" + getId())
                .add("Score=" + getScore())
                .toString();
    }// endregion toString()
    // endregion Constructor, getters, setters, equals, hashCode, toString
}
